// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"double/app/club/internal/biz"
	"double/app/club/internal/conf"
	"double/app/club/internal/data"
	"double/app/club/internal/server"
	"double/app/club/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
// 添加*conf.Registry配置参数，用于在data中注入NewRegistrar
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	clubRepo := data.NewClubRepo(dataData, logger)
	clubUsecase := biz.NewClubUsecase(clubRepo, logger)
	clubService := service.NewClubService(clubUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, clubService, logger)
	grpcServer := server.NewGRPCServer(confServer, clubService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
