#添加trace（需要提前开启jaeger容器）
#下面的内容仅用于本地调试，线上需要上传的配置中心。配置key在registry.yaml
trace:
  endpoint: http://host.docker.internal:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1.2s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1.2s
data:
  database:
    driver: mysql
    source: root:root@tcp(host.docker.internal:3306)/test
  redis:
    addr: host.docker.internal:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 11
