#添加trace（需要提前开启jaeger容器）
trace:
  endpoint: http://host.docker.internal:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1.2s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1.2s
data:
  database:
    driver: mysql
    source: root:root@tcp(host.docker.internal:3306)/test
  redis:
    addr: host.docker.internal:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 11
