// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.0

package club_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ClubHTTPServer interface {
	GetClub(context.Context, *GetClubRequest) (*GetClubReply, error)
}

func RegisterClubHTTPServer(s *http.Server, srv ClubHTTPServer) {
	r := s.Route("/")
	r.GET("v1/club/{id}", _Club_GetClub0_HTTP_Handler(srv))
}

func _Club_GetClub0_HTTP_Handler(srv ClubHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetClubRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.club.v1.Club/GetClub")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetClub(ctx, req.(*GetClubRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetClubReply)
		return ctx.Result(200, reply)
	}
}

type ClubHTTPClient interface {
	GetClub(ctx context.Context, req *GetClubRequest, opts ...http.CallOption) (rsp *GetClubReply, err error)
}

type ClubHTTPClientImpl struct {
	cc *http.Client
}

func NewClubHTTPClient(client *http.Client) ClubHTTPClient {
	return &ClubHTTPClientImpl{client}
}

func (c *ClubHTTPClientImpl) GetClub(ctx context.Context, in *GetClubRequest, opts ...http.CallOption) (*GetClubReply, error) {
	var out GetClubReply
	pattern := "v1/club/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.club.v1.Club/GetClub"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
