// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package club_v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsClubNotFound(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CLUB_NOT_FOUND.String() && e.Code == 404
}

func ErrorClubNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_CLUB_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
